version: '3.5'
services:
  service-schedule:
    image: migsking/dms-sms-service-schedule:${VERSION}
    container_name: service-schedule
    networks:
      - dms-sms-local
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - CONSUL_ADDR=${CONSUL_ADDRESS}
      - JAEGER_AGENT_HOST=${JAEGER_HOST}
      - JAEGER_AGENT_PORT=${JAEGER_PORT}

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: bridge