spring:
  main:
    web-application-type: none
  jpa:
    properties:
      hibernate:
        ejb:
          interceptor: dsm.service.schedule.infra.config.db.mysql.MysqlInterceptor
    hibernate:
      ddl-auto: update
    generate-ddl: true

schedule:
  schoolApi:
    key: ${API_KEY}

grpc:
  port: 0